"""empty message

Revision ID: d6ebb84cfe98
Revises: 91045b3e822a
Create Date: 2019-04-14 15:41:39.703145

"""
from alembic import op
import sqlalchemy as sa
from migrations import reader



# revision identifiers, used by Alembic.
revision = 'd6ebb84cfe98'
down_revision = '91045b3e822a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    chains = op.create_table('bi-vistor-chain-totals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('ChainID', sa.String, nullable=True),
    sa.Column('LOCATION', sa.String(), nullable=True),
    sa.Column('Mild', sa.Integer(), nullable=True),
    sa.Column('Moderate', sa.Integer(), nullable=True),
    sa.Column('Frequent', sa.Integer(), nullable=True),
    sa.Column('AudienceTotal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    Chaindata = reader.readMyFiles('chain.csv')
    print(' insert chains')
    op.bulk_insert(chains, Chaindata)   


    totalTables = op.create_table('bi-vsistor-level-totals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('Level_1', sa.String(), nullable=True),
    sa.Column('Level_2', sa.String(), nullable=True),
    sa.Column('Mild', sa.Integer(), nullable=True),
    sa.Column('Moderate', sa.Integer(), nullable=True),
    sa.Column('Frequent', sa.Integer(), nullable=True),
    sa.Column('AudienceTotal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    Totaldata = reader.readMyFiles('total.csv')
    print('insertingvalues')
    op.bulk_insert(totalTables, Totaldata)   



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bi-vsistor-level-totals')
    op.drop_table('bi-vistor-chain-totals')
    # ### end Alembic commands ###
