"""empty message

Revision ID: d7cfbfca4c9c
Revises: d6ebb84cfe98
Create Date: 2019-04-14 16:12:48.282022

"""
from alembic import op
import sqlalchemy as sa
from migrations import reader


# revision identifiers, used by Alembic.
revision = 'd7cfbfca4c9c'
down_revision = 'd6ebb84cfe98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    vistorTables = op.create_table('Visitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID', sa.String, nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('Level_1', sa.String(), nullable=True),
    sa.Column('Level_2', sa.String(), nullable=True),
    sa.Column('ChainID', sa.Float(), nullable=True),
    sa.Column('LOCATION', sa.String(), nullable=True),
    sa.Column('Mild', sa.Integer(), nullable=True),
    sa.Column('Moderate', sa.Integer(), nullable=True),
    sa.Column('Frequent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    data = reader.readMyFiles('base.csv')
    op.bulk_insert(vistorTables, data)   


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Visitors')
    # ### end Alembic commands ###
